version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
    - liamnichols
  versioning-strategy: lockfile-only
  insecure-external-code-execution: allow
